### ISSUE TITLE
[路线错误] 黑塔空间站-收容舱段

### ISSUE THREAD

**Issue by 246182606** [Starry-Wind/SRA#218]
### 问题描述

地图编号：1-2_1
问题描述：
未按照预定路线走
![2023-05-17_210404](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/59857158/d366bf31-7c94-42ae-be4f-7f7d1e7466db)
![2023-05-17_210436](https://github.com/Starry-Wind/Honkai-Star-Rail/assets/59857158/6244689d-43b5-473e-8acf-74f36f7f84a5)

### 是否使用三月七跑图

- [X] 是
- [ ] 否

### 日志

21:03:04 - DEBUG	| map.auto_map:32 - 3.1 -  ['map_1-1_1.json', 'map_1-2_1.json', 'map_1-2_2.json', 'map_1-2_3.json', 'map_1-2_4.json', 'map_1-3_1.json', 'map_1-3_2.json', 'map_1-3_3.json', 'map_1-3_4.json', 'map_2-1_1.json', 'map_2-1_2.json', 'map_2-2_1.json', 'map_2-2_2.json', 'map_2-3_1.json', 'map_2-3_2.json', 'map_2-3_3.json', 'map_2-3_4.json', 'map_2-3_5.json', 'map_2-4_1.json', 'map_2-4_2.json', 'map_2-5_1.json', 'map_2-5_2.json', 'map_2-5_3.json', 'map_2-5_4.json', 'map_2-6_1.json', 'map_2-6_2.json', 'map_2-7_1.json', 'map_2-7_2.json', 'map_2-7_3.json', 'map_3-1_1.json', 'map_3-1_2.json', 'map_3-1_3.json', 'map_3-1_4.json', 'map_3-2_1.json', 'map_3-2_2.json', 'map_3-2_3.json', 'map_3-2_4.json', 'map_3-2_5.json', 'map_3-3_1.json', 'map_3-3_2.json', 'map_3-3_3.json', 'map_3-3_4.json', 'map_3-4_1.json', 'map_3-4_2.json', 'map_3-4_3.json', 'map_3-4_4.json', 'map_3-4_5.json', 'map_3-4_6.json']
21:03:04 - INFO	| log.webhook_and_log:37 - 3.1 -  开始[0;34;40m收容舱段-1[0m锄地
21:03:04 - INFO	| map.auto_map:43 - 3.1 -  该路线导航作者：[0;31;40mStarry-Wind,小明[0m
21:03:04 - INFO	| map.auto_map:44 - 3.1 -  感谢每一位无私奉献的作者
21:03:04 - DEBUG	| map.auto_map:47 - 3.1 -  map
21:03:06 - DEBUG	| map.map_init:26 - 3.1 -  (631, 986)
21:03:06 - DEBUG	| map.auto_map:47 - 3.1 -  temp\orientation_1.jpg
21:03:08 - DEBUG	| calculated.Click:33 - 3.1 -  (1644, 137)
21:03:09 - DEBUG	| map.auto_map:47 - 3.1 -  temp\orientation_2.png
21:03:11 - DEBUG	| calculated.Click:33 - 3.1 -  (261, 486)
21:03:11 - DEBUG	| map.auto_map:47 - 3.1 -  temp\map_1-2.jpg
21:03:14 - DEBUG	| calculated.Click:33 - 3.1 -  (1550, 521)
21:03:14 - DEBUG	| map.auto_map:47 - 3.1 -  temp\map_1-2_point_1.jpg
21:03:16 - DEBUG	| calculated.Click:33 - 3.1 -  (546, 560)
21:03:17 - DEBUG	| map.auto_map:47 - 3.1 -  temp\transfer.jpg
21:03:19 - DEBUG	| calculated.Click:33 - 3.1 -  (1659, 971)
21:03:24 - INFO	| calculated.auto_map:154 - 3.1 -  开始寻路
21:03:24 - INFO	| calculated.auto_map:156 - 3.1 -  执行map_1-2_1文件:1/8 {'d': 3.5159339904785156}
21:03:28 - INFO	| calculated.auto_map:156 - 3.1 -  执行map_1-2_1文件:2/8 {'w': 4.1744420528411865}
21:03:32 - INFO	| calculated.auto_map:156 - 3.1 -  执行map_1-2_1文件:3/8 {'fighting': 1}
21:03:32 - INFO	| calculated.fighting:109 - 3.1 -  识别中
21:03:32 - DEBUG	| calculated.Click:33 - 3.1 -  (977, 932)

**Comment by weiduhuo** [comment]
路线本身没错，我认为是因为你的地图加载时间过长（大于预设的5秒休眠）导致，相关问题已[在此](https://github.com/Starry-Wind/Honkai-Star-Rail/issues/216)反馈，并提出了修改建议

**Comment by Klamist** [comment]
这段我是没问题的。。
